steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/my-test-repo/shubham", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/my-test-repo/shubham"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./kubernetes-manifests/
  - --location=us-central1
  - --cluster=cluster-1
- name: "gcr.io/cloud-builders/kubectl"
  args:
      - rollout
      - restart
      - deployment/nginx-testing
      - --ignore-not-found
  env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
options:
  logging: CLOUD_LOGGING_ONLY