apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-testing
  name: nginx-testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-testing
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-testing
    spec:
      containers:
        - image: gcr.io/excellent-grove-424408-h3/my-test-repo/shubham:latest 
          name: nginx