apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp1
  name: myapp1-loadbalancer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-testing 
  type: LoadBalancer